# Generated by Django 5.2.17 on 2026-08-13 02:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Banking / Financial Services', 'Banking / Financial Services'), ('Education / Training', 'Education / Training'), ('Healthcare / Medical', 'Healthcare / Medical'), ('Sales & Business Development', 'Sales & Business Development'), ('Marketing & Advertising', 'Marketing & Advertising'), ('Manufacturing', 'Manufacturing'), ('E-Commerce', 'E-Commerce'), ('Telecommunications', 'Telecommunications'), ('Real Estate / Property', 'Real Estate / Property'), ('Call Center / BPO', 'Call Center / BPO'), ('NGO / Social Services', 'NGO / Social Services'), ('Travel / Tourism', 'Travel / Tourism'), ('Logistics / Supply Chain', 'Logistics / Supply Chain'), ('Retail', 'Retail'), ('Construction / Engineering', 'Construction / Engineering'), ('Textiles / Fashion', 'Textiles / Fashion'), ('Food & Beverage', 'Food & Beverage')], max_length=80)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employees', models.CharField(blank=True, help_text='e.g. 51-200', max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(blank=True, help_text='Employer account that manages this company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('software', 'Software & Web Development'), ('design', 'Creative Design'), ('marketing', 'Marketing & Communications'), ('sales', 'Sales & BD'), ('accounts', 'Accounts & Finance'), ('hr', 'Human Resources'), ('admin', 'Administration'), ('customer', 'Customer Service'), ('teaching', 'Teaching & Education'), ('health', 'Health & Medicine'), ('engineering', 'Engineering'), ('operations', 'Operations / Management'), ('writing', 'Writing & Content'), ('logistics', 'Logistics & Distribution'), ('other', 'Other')], default='other', max_length=40)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('remote', 'Remote'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('fresh', 'Fresh Graduate'), ('junior', 'Entry Level (1-2 yrs)'), ('mid', 'Mid Level (3-5 yrs)'), ('senior', 'Senior Level (5+ yrs)'), ('lead', 'Manager / Lead')], default='fresh', max_length=20)),
                ('city', models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Gujranwala', 'Gujranwala'), ('Sialkot', 'Sialkot'), ('Hyderabad', 'Hyderabad'), ('Sargodha', 'Sargodha'), ('Bahawalpur', 'Bahawalpur'), ('Abbottabad', 'Abbottabad'), ('Murree', 'Murree'), ('Gujrat', 'Gujrat'), ('Jhelum', 'Jhelum'), ('Sahiwal', 'Sahiwal'), ('Gawadar', 'Gawadar'), ('Remote / Anywhere', 'Remote / Anywhere')], max_length=60)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('salary_period', models.CharField(choices=[('monthly', 'per month'), ('annual', 'per year'), ('hourly', 'per hour')], default='monthly', max_length=10)),
                ('description', models.TextField(help_text='What the job involves.')),
                ('responsibilities', models.TextField(blank=True, help_text='One bullet point per line.')),
                ('requirements', models.TextField(blank=True, help_text='One bullet point per line.')),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills.', max_length=300)),
                ('apply_method', models.CharField(choices=[('email', 'Apply by email'), ('url', 'Apply on website')], default='email', max_length=10)),
                ('apply_email', models.EmailField(blank=True, max_length=254)),
                ('apply_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='applications/resumes/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='received', max_length=15)),
                ('note', models.CharField(blank=True, help_text='Private note for the employer.', max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'posted_at'], name='jobs_job_status_60011a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['city'], name='jobs_job_city_e9517f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category'], name='jobs_job_categor_653d6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
