# Generated by Django 5.2.17 on 2026-08-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(blank=True, help_text='Keyword search.', max_length=120)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, choices=[('software', 'Software & Web Development'), ('design', 'Creative Design'), ('marketing', 'Marketing & Communications'), ('sales', 'Sales & BD'), ('accounts', 'Accounts & Finance'), ('hr', 'Human Resources'), ('admin', 'Administration'), ('customer', 'Customer Service'), ('teaching', 'Teaching & Education'), ('health', 'Health & Medicine'), ('engineering', 'Engineering'), ('operations', 'Operations / Management'), ('writing', 'Writing & Content'), ('logistics', 'Logistics & Distribution'), ('other', 'Other')], max_length=40)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('remote', 'Remote'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=10)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('email', 'query', 'city', 'category', 'job_type'), name='uniq_job_alert_subscription')],
            },
        ),
    ]
